services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    networks:
      someip_net:
        ipv4_address: 192.168.0.101
    cap_add:
      - NET_ADMIN
    privileged: true
    stdin_open: true
    tty: true

  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    networks:
      someip_net:
        ipv4_address: 192.168.0.102
    cap_add:
      - NET_ADMIN
    privileged: true
    stdin_open: true
    tty: true
    depends_on:
      - server

  attacker:
    build:
      context: .
      dockerfile: Dockerfile
      target: attacker
    networks:
      someip_net:
        ipv4_address: 192.168.0.104
    cap_add:
      - NET_ADMIN
    privileged: true
    tty: true
    environment:
      - INTERFACE=eth0
      - BROADCAST_IP=224.224.224.245
      - TIMEOUT=120
      - DEBUG=True
    depends_on:
      - server
      - client
    profiles:
      - donotstart # Prevents starting by default

networks:
  someip_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
